### ISSUE TITLE
Plugin activation problem

### ISSUE THREAD

**Issue by gcapnias** [lymperis-e/Greek-Data-QGIS-Plugin#1]
Hi nice work!

I didn't want the plugin, to be visible all the time. So I closed it, and later, when I needed to load more data, I pressed the button on the toolbar to open it again.

Every time the plugin is loaded, the list with the providers is loaded again. You can see the list, two, three times, as many time you open and close the plugin.

The plugin should only load once the providers list.

George J.

**Comment by lymperis-e** [comment]
George, thank you very much for your feedback! Your suggestion is very much correct and I will be implementing that as soon as possible
