### ISSUE TITLE
Provider connection problem

### ISSUE THREAD

**Issue by gcapnias** [lymperis-e/Greek-Data-QGIS-Plugin#2]
Hi,

When you choose a provider, the plugin tries to download the list of the provider's availiable layers list.
When you open the plugin again and again, the plugin crashes with the application.

I think, there should be a connect/disconnect button in order the user controls the update of the list of layers.

George J.

**Comment by lymperis-e** [comment]
George, thank you very much for your feedback, I am sorry to take so long to respond. I will be commiting to the project more closely from now on. This is a valid point you are making and will be implementing that in the next release. Until then I am leaving the issue open
